name: tahfidz
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  advance_notification: ^1.0.6
  animated_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  http: ^0.13.4
  image_picker: ^0.8.4+11
  line_icons: ^2.0.1
  lottie: ^1.2.2
  sp_util: null
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
